Added a bog page, descriptions to the feature section, and Rindra and Obeda in the Our team section.
Tenafli/tenafli.github.io pull request #6
Opened 2023-12-15 21:31 UTC by dah000

2023-12-16 00:44 UTC, andy-ratsirarson requested changes

2023-12-16 00:44 UTC, andy-ratsirarson commented on blog.html
> +			<!-- <div class="blog-container fs-5">
is this commented section needed? if not, let's delete it.

2023-12-16 00:44 UTC, andy-ratsirarson commented on assets/img/team/Rindra.jpg
@rindra-rolando can you provide a profile with a one-color background to be put on our site.

2023-12-16 00:44 UTC, andy-ratsirarson commented on assets/img/team/Rindra.jpg
@maharo-raj can you provide a profile as well. Thanks

2023-12-19 08:00 UTC, dah000 commented on blog.html
> +			<!-- <div class="blog-container fs-5">
No it's not. I removed it.

2024-01-04 14:28 UTC, andy-ratsirarson approved these changes

2024-01-04 14:28 UTC, merged